version: "3.3"

services:
  ubuntu:
    build:
      context: ./servidor
    container_name: Ubuntu
    stdin_open: true
    tty: true
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./servidor:/srv
    depends_on:
      - db

  web:
    build:
      context: ./website
    container_name: Site
    volumes:
      - ./servidor/datapack:/srv
      - ./website/html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      - ubuntu

  db:
    image: mysql:5.7
    container_name: BancoDeDados
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: otserv
      MYSQL_PASSWORD: 1234
    volumes:
      - ./servidor/schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  dbAdminPainel:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: AdminBancoDeDados
    restart: always
    ports:
      - 1010:80
    links:
      - db
    environment:
      PMA_ARBITRARY: 1