version: '3'

services: 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: server1010
    volumes:
      - ./server-ntoglobal/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build:
      context: ./website-ntoglobal
    container_name: web
    links:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./website-ntoglobal/:/usr/share/nginx/html
      - ./server-ntoglobal:/home/server-ntoglobal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 1010:80
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1

  server:
    build:
      context: ./server-ntoglobal
    ports:
      - 7171:7171
      - 7172:7172
    volumes:
      - ./server-ntoglobal:/home/server-ntoglobal
    depends_on:
      - mysql
      - web
    stdin_open: true 
    tty: true
