FROM r0bert0lol/server-ntoglobal:0.0.8

COPY . /home/server-ntoglobal

RUN chmod 7777 /home/server-ntoglobal

WORKDIR /home/server-ntoglobal

EXPOSE 7171 7172

CMD [ "/home/server-ntoglobal/theotxcombat" ]